### ISSUE TITLE
How to generate category_id and category_rev

### ISSUE THREAD

**Issue by abc123yuanrui** [Charleshhy/Grapy-ML#6]
as title, why we need cat and cat_flip? how to get those from vanilla images since it seems to me they are already segmentation results

**Comment by Charleshhy** [comment]
Hi, the flipped segmentation masks are used for data augmentation during training and more robust evaluation during testing. Training with flipped masks can significantly improve the parsing performance. The flipped masks are provided in [this](https://github.com/Gaoyiminggithub/Graphonomy) repository.
