### ISSUE TITLE
How to prepare the different level of category mask? Thanks!

### ISSUE THREAD

**Issue by Minssnail** [Charleshhy/Grapy-ML#7]

**Comment by Charleshhy** [comment]
Hello! Each parent coarse-grind category mask is generated by aggregating the pixels of child fine-grind categories.

The parent-children category relationships are pre-defined [here](https://github.com/Charleshhy/Grapy-ML/blob/master/exp/refine_on_datasets_SYN/train_gpm_ml.py#L321) in L321.

**Comment by Minssnail** [comment]
> Hello! Each parent coarse-grind category mask is generated by aggregating the pixels of child fine-grind categories.
> 
> The parent-children category relationships are pre-defined [here](https://github.com/Charleshhy/Grapy-ML/blob/master/exp/refine_on_datasets_SYN/train_gpm_ml.py#L321) in L321.

Thanks a lot!
